base_controller:
  type: "robot_controllers/DiffDriveBaseController"
  max_velocity_x: 1.5
  max_acceleration_x: 2.0
  # hold position
  moving_threshold: -0.01
  rotating_threshold: -0.01
  # autostart to get odom
  autostart: true
  # use laser to only slowly collide with things
  laser_safety_dist: 1.5

robot_driver:
  default_controllers:
    - "base_controller"
